### ISSUE TITLE
UITableView添加IndicatorFooter后， Row点击事件不响应

### ISSUE THREAD

**Issue by Joe0708** [WXGBridgeQ/SwiftPullToRefresh#1]
`scrollView.spr_addIndicatorFooter { [weak self] in
    // do your action here
    // self?.scrollView.spr_endRefreshing()
}`

我使用spr_addIndicatorFooter给UITableView添加了一个上拉加载控件，但是点击cell时 **didSelectRowAt** 不再响应？我把添加IndicatorFooter相关代码注释后一切正常，请问是bug，还是我代码问题？

**Comment by Joe0708** [comment]
我使用提供的Demo， 给UITableView添加加载控件之后， 同样无法响应cell的点击事件？请尽快解决，谢谢

**Comment by WXGBridgeQ** [comment]
@Joe0708 
多谢提醒，确实是我的代码有问题，已经在修复了。

**Comment by WXGBridgeQ** [comment]
@Joe0708 
你好，我在0.2.3版本里面修复了这个问题，你可以再试一下。
再次表示感谢。
