### ISSUE TITLE
Crash when run on IOS 10.3.3

### ISSUE THREAD

**Issue by baohung02** [WXGBridgeQ/SwiftPullToRefresh#19]
It works well on iOS 11.3, but failed on 10.3.3 with logs:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x19be2e10 of class UIScrollViewPanGestureRecognizer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x19a8cef0> (
<NSKeyValueObservance 0x17f6c4d0: Observer: 0x17fa5550, Key path: state, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x17f60500>
<NSKeyValueObservance 0x19ab9180: Observer: 0x19a1d950, Key path: state, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x17f60500>
)'

I guess problem happen when you didn't remove observer in RefreshView.

**Comment by WXGBridgeQ** [comment]
@baohung02 
Sorry for the late response, already fixed the issue in the latest version (v2.4.2), you can try again.
Thanks for your help.

**Comment by baohung02** [comment]
Nice, thank you.

**Comment by s-reshetnikov** [comment]
Hi, @WXGBridgeQ, I catch the same issue at ios 10.3.1 after update pod to 2.4.2.

**Comment by WXGBridgeQ** [comment]
@s-reshetnikov 
Fixed in 2.4.3, please have a try with the new version.
