### ISSUE TITLE
请问在RefreshBaseView类中定义refreshViewDelegate属性有什么意图吗

### ISSUE THREAD

**Issue by eppeo** [WXGBridgeQ/SwiftPullToRefresh#2]
在这个类中实现协议代理方法，只是为了便于子类重写再调用吗，并且还用到了KVO又是为什么？

**Comment by WXGBridgeQ** [comment]
@eppeo 
最早使用代理的方式来实现，是为了下拉松手时的流畅，后来发现这种方式有问题，忽略了tableViewDelegate的情况，新版本已改为只使用KVO实现。
多谢关注。
