### ISSUE TITLE
Wrong content offset on iOS 11+ when using navigation bar and/or tab bar

### ISSUE THREAD

**Issue by n3d1117** [WXGBridgeQ/SwiftPullToRefresh#21]
Hello! I've been noticing a small bug when using SwiftPullToRefresh together with a navigation bar and a tab bar on iOS 11 or higher (works fine on iOS 10).
The indicator arrow doesn't seem to animate at the correct height. 

[Here's a video comparison between iOS 10 and iOS 11 behavior](https://github.com/WXGBridgeQ/SwiftPullToRefresh/files/2455626/TestSwiftPullToRefresh.mov.zip).

[And here's the sample project](https://github.com/WXGBridgeQ/SwiftPullToRefresh/files/2455627/TestSwiftPullToRefresh.zip).

Thanks for your help.

**Comment by WXGBridgeQ** [comment]
@n3d1117 
The issue was fixed in version 2.4.8, thanks for your information.
