### ISSUE TITLE
Changes in v2.4.5 broke indicator views when switching between tabs

### ISSUE THREAD

**Issue by n3d1117** [WXGBridgeQ/SwiftPullToRefresh#22]
Hello!

Latest commit broke indicator views when switching between tabs, see here:

<p align="center"><img src="https://user-images.githubusercontent.com/11541888/46662993-28e2a680-cbbd-11e8-87dc-ebcb00784a45.gif" width="200" height="354"/></p>

Sample project can be downloaded [here](https://github.com/WXGBridgeQ/SwiftPullToRefresh/files/2459945/TestSwiftPullToRefresh.2.zip).

Reverting to v2.4.4 works fine. 
I think the issue is that in v2.4.5 you moved the code to update tokens in `RefreshView.swift` from `func willMove(toWindow newWindow: UIWindow?)` to `func willMove(toSuperview newSuperview: UIView?)`, but the latter isn't called when switching between tabs, so indicators are not updated properly.

A possible solution is to call the same code in both functions, but there should be a better one.

Thanks for your help!

**Comment by WXGBridgeQ** [comment]
Fixed in the new version 2.4.6
Thanks.
