### ISSUE TITLE
刷新完成之后，reloadData 刷新视图，会闪一下。

### ISSUE THREAD

**Issue by sunapollo** [WXGBridgeQ/SwiftPullToRefresh#3]
不论是下拉，还是上拉都会出现这样的情况。

**Comment by WXGBridgeQ** [comment]
@sunapollo 
你好，我自己测了一下，并不会发生你说的情况。
应该不是我代码的问题，推荐你再检查下你自己的代码。

如需帮助可以发我邮件。
