### ISSUE TITLE
没有移除刷新控件的方法

### ISSUE THREAD

**Issue by XHQFighting** [WXGBridgeQ/SwiftPullToRefresh#6]
在很多情况下，比如上啦加载更多，一开始有，后来全部数据加载完了，就要移除刷新控件，你少写了个移除方法（或者我看漏了哪个文件，没找到），可以添加一下嘛，谢谢啦😀

**Comment by WXGBridgeQ** [comment]
多谢提醒，目前确实没有，打算尽快加上。

**Comment by WXGBridgeQ** [comment]
@XHQFighting 
新版本已经可以移除footer了，API去代码里看一眼就好了。
多谢反馈。
