### ISSUE TITLE
Cannot pull down to refresh unless the scrollable area height is bigger than the device height

### ISSUE THREAD

**Issue by serkanbal** [WXGBridgeQ/SwiftPullToRefresh#8]
Thanks for the pod; works like a charm!

Have a slight issue though. The pull down to refresh is working great if the scrollView is actually scrollable; meaning that its content height is bigger than the device height. However; if the scrollView is not scrollable because its content's height is not bigger than the device height; I cannot pull down to refresh. To better illustrate; I am adding 2 videos to show my issue.

What can I do to enable pull to refresh in the second case?

First Vid:
Scrollview is scrollable because its content height is bigger than device height. Pull to refresh working:
[https://www.dropbox.com/s/8svkh5ntag5znfo/vid1.mov?dl=0](https://www.dropbox.com/s/8svkh5ntag5znfo/vid1.mov?dl=0)

Second Vid:
Scrollview is not scrollable because its content height is smaller than device height. Pull to refresh is not working:
[https://www.dropbox.com/s/v80yk4s1c0fsg2a/vid2.mov?dl=0](https://www.dropbox.com/s/v80yk4s1c0fsg2a/vid2.mov?dl=0)

**Comment by WXGBridgeQ** [comment]
@serkanbal 
Hi, thanks for your comment, and also the clear video demo.

I have tried with my own, if you turn on the `Bounce Vertically`, which means set the  `alwaysBounceVertical` property of the scrollView to be `true`, then the refresh control will work.

Hope it works as your requirement.
